# Generated by Django 2.0.6 on 2018-06-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname_id', models.CharField(max_length=120)),
                ('u_id', models.CharField(max_length=120, null=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TargetedHashTagUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TargetHashTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htags', models.CharField(max_length=120)),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.LoginData')),
            ],
        ),
        migrations.CreateModel(
            name='TargetUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=120)),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.LoginData')),
            ],
        ),
        migrations.AddField(
            model_name='targetedhashtagusers',
            name='targethashtags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.TargetHashTags'),
        ),
        migrations.AddField(
            model_name='followers',
            name='targetusers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.TargetUsers'),
        ),
    ]
