# Generated by Django 2.0.6 on 2018-06-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfigurationsstate',
            name='to_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
