# Generated by Django 2.0.6 on 2018-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20180627_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
